# Setup
title:               Learning Large-Scale System Design
tagline:             ' by a network architect.'
description:         'How I would have designed them, understand why web-scale solution was chosen and where network solutions could have improved the overall outcome.'
url:                  https://kiranmak.github.io
baseurl:              /sysarch
repository :         "kiranmak/sysarch"
paginate:            5
permalink:           pretty
website:             https://kiranmak.github.io
basewebsite:         /sysarch

# About/contact
author:
  name:              Kiran Makhijani
  email:             kiranmak@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
